parameters:
  word_press_ibexa.default.url: true
  word_press_ibexa.posts: []
  word_press_ibexa.pages: []
  word_press_ibexa.tags: []
  word_press_ibexa.categories: []
  word_press_ibexa.image: []
  word_press_ibexa.media: []
  word_press_ibexa.default.webroot_dir: '%kernel.project_dir%/public'
  word_press_ibexa.default.local_image_root_dir: '/tmp/wordpress_images/'
  word_press_ibexa.default.image_separator: '__'
