services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true
        bind:
            $cachePool: '@ibexa.cache_pool'

    Almaviacx\Bundle\Ibexa\WordPress\Service\:
        resource: '../../Service'
#        lazy: true

    Almaviacx\Bundle\Ibexa\WordPress\Command\:
        resource: '../../Command'
        lazy: true